# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_transfer.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'data_transfer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64\x61ta_transfer.proto\x12\x0c\x64\x61tatransfer\"\x8e\x02\n\x12\x43ollisionRecordMsg\x12\x12\n\ncrash_date\x18\x01 \x01(\x05\x12\x12\n\ncrash_time\x18\x02 \x01(\x05\x12\x17\n\x0fpersons_injured\x18\x03 \x01(\x05\x12\x16\n\x0epersons_killed\x18\x04 \x01(\x05\x12\x1b\n\x13pedestrians_injured\x18\x05 \x01(\x05\x12\x1a\n\x12pedestrians_killed\x18\x06 \x01(\x05\x12\x18\n\x10\x63yclists_injured\x18\x07 \x01(\x05\x12\x17\n\x0f\x63yclists_killed\x18\x08 \x01(\x05\x12\x19\n\x11motorists_injured\x18\t \x01(\x05\x12\x18\n\x10motorists_killed\x18\n \x01(\x05\"4\n\x10SendDataResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"C\n\x0fSendDataRequest\x12\x30\n\x06record\x18\x01 \x01(\x0b\x32 .datatransfer.CollisionRecordMsg2\xab\x01\n\x0c\x44\x61taTransfer\x12I\n\x08SendData\x12\x1d.datatransfer.SendDataRequest\x1a\x1e.datatransfer.SendDataResponse\x12P\n\nStreamData\x12 .datatransfer.CollisionRecordMsg\x1a\x1e.datatransfer.SendDataResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_transfer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COLLISIONRECORDMSG']._serialized_start=38
  _globals['_COLLISIONRECORDMSG']._serialized_end=308
  _globals['_SENDDATARESPONSE']._serialized_start=310
  _globals['_SENDDATARESPONSE']._serialized_end=362
  _globals['_SENDDATAREQUEST']._serialized_start=364
  _globals['_SENDDATAREQUEST']._serialized_end=431
  _globals['_DATATRANSFER']._serialized_start=434
  _globals['_DATATRANSFER']._serialized_end=605
# @@protoc_insertion_point(module_scope)
